// <auto-generated />
using System;
using EquifaxEnrichmentAPI.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EquifaxEnrichmentAPI.Infrastructure.Migrations
{
    [DbContext(typeof(EnrichmentDbContext))]
    [Migration("20251104015053_RemoveNormalizedPhoneConfiguration")]
    partial class RemoveNormalizedPhoneConfiguration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EquifaxEnrichmentAPI.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("BuyerId")
                        .HasColumnType("uuid")
                        .HasColumnName("buyer_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip_address");

                    b.Property<string>("PermissiblePurpose")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("permissible_purpose");

                    b.Property<string>("PhoneHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("phone_hash");

                    b.Property<string>("Response")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("response");

                    b.Property<int>("StatusCode")
                        .HasColumnType("integer")
                        .HasColumnName("status_code");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("timestamp")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp")
                        .IsDescending()
                        .HasDatabaseName("ix_audit_logs_timestamp");

                    b.HasIndex("BuyerId", "Timestamp")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_audit_logs_buyer_id_timestamp");

                    b.HasIndex("PhoneHash", "Timestamp")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_audit_logs_phone_hash_timestamp");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("EquifaxEnrichmentAPI.Domain.Entities.Buyer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ApiKeyHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("api_key_hash");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ApiKeyHash")
                        .IsUnique()
                        .HasDatabaseName("ix_buyers_api_key_hash_unique");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_buyers_created_at");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_buyers_is_active");

                    b.ToTable("buyers", (string)null);
                });

            modelBuilder.Entity("EquifaxEnrichmentAPI.Domain.Entities.ConsumerEnrichment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("address_1")
                        .HasColumnType("text");

                    b.Property<string>("address_10")
                        .HasColumnType("text");

                    b.Property<string>("address_2")
                        .HasColumnType("text");

                    b.Property<string>("address_3")
                        .HasColumnType("text");

                    b.Property<string>("address_4")
                        .HasColumnType("text");

                    b.Property<string>("address_5")
                        .HasColumnType("text");

                    b.Property<string>("address_6")
                        .HasColumnType("text");

                    b.Property<string>("address_7")
                        .HasColumnType("text");

                    b.Property<string>("address_8")
                        .HasColumnType("text");

                    b.Property<string>("address_9")
                        .HasColumnType("text");

                    b.Property<decimal?>("affluence_index")
                        .HasColumnType("numeric");

                    b.Property<string>("age")
                        .HasColumnType("text");

                    b.Property<string>("alternate_first_name_1")
                        .HasColumnType("text");

                    b.Property<string>("alternate_first_name_2")
                        .HasColumnType("text");

                    b.Property<string>("alternate_first_name_3")
                        .HasColumnType("text");

                    b.Property<string>("alternate_first_name_4")
                        .HasColumnType("text");

                    b.Property<string>("alternate_first_name_5")
                        .HasColumnType("text");

                    b.Property<string>("alternate_last_name_1")
                        .HasColumnType("text");

                    b.Property<string>("alternate_last_name_2")
                        .HasColumnType("text");

                    b.Property<string>("alternate_last_name_3")
                        .HasColumnType("text");

                    b.Property<string>("alternate_last_name_4")
                        .HasColumnType("text");

                    b.Property<string>("alternate_last_name_5")
                        .HasColumnType("text");

                    b.Property<string>("alternate_middle_name_1")
                        .HasColumnType("text");

                    b.Property<string>("alternate_middle_name_2")
                        .HasColumnType("text");

                    b.Property<string>("alternate_middle_name_3")
                        .HasColumnType("text");

                    b.Property<string>("alternate_middle_name_4")
                        .HasColumnType("text");

                    b.Property<string>("alternate_middle_name_5")
                        .HasColumnType("text");

                    b.Property<string>("alternate_name_1")
                        .HasColumnType("text");

                    b.Property<string>("alternate_name_2")
                        .HasColumnType("text");

                    b.Property<string>("alternate_name_3")
                        .HasColumnType("text");

                    b.Property<string>("alternate_name_4")
                        .HasColumnType("text");

                    b.Property<string>("alternate_name_5")
                        .HasColumnType("text");

                    b.Property<string>("alternate_prefix_1")
                        .HasColumnType("text");

                    b.Property<string>("alternate_prefix_2")
                        .HasColumnType("text");

                    b.Property<string>("alternate_prefix_3")
                        .HasColumnType("text");

                    b.Property<string>("alternate_prefix_4")
                        .HasColumnType("text");

                    b.Property<string>("alternate_prefix_5")
                        .HasColumnType("text");

                    b.Property<string>("alternate_suffix_1")
                        .HasColumnType("text");

                    b.Property<string>("alternate_suffix_2")
                        .HasColumnType("text");

                    b.Property<string>("alternate_suffix_3")
                        .HasColumnType("text");

                    b.Property<string>("alternate_suffix_4")
                        .HasColumnType("text");

                    b.Property<string>("alternate_suffix_5")
                        .HasColumnType("text");

                    b.Property<decimal?>("auto_in_market_propensity_score")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("automotive_response_intent_indicator")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("balance_auto_finance_loan_accounts")
                        .HasColumnType("numeric");

                    b.Property<string>("carrier_route_1")
                        .HasColumnType("text");

                    b.Property<string>("carrier_route_10")
                        .HasColumnType("text");

                    b.Property<string>("carrier_route_2")
                        .HasColumnType("text");

                    b.Property<string>("carrier_route_3")
                        .HasColumnType("text");

                    b.Property<string>("carrier_route_4")
                        .HasColumnType("text");

                    b.Property<string>("carrier_route_5")
                        .HasColumnType("text");

                    b.Property<string>("carrier_route_6")
                        .HasColumnType("text");

                    b.Property<string>("carrier_route_7")
                        .HasColumnType("text");

                    b.Property<string>("carrier_route_8")
                        .HasColumnType("text");

                    b.Property<string>("carrier_route_9")
                        .HasColumnType("text");

                    b.Property<string>("city_name_1")
                        .HasColumnType("text");

                    b.Property<string>("city_name_10")
                        .HasColumnType("text");

                    b.Property<string>("city_name_2")
                        .HasColumnType("text");

                    b.Property<string>("city_name_3")
                        .HasColumnType("text");

                    b.Property<string>("city_name_4")
                        .HasColumnType("text");

                    b.Property<string>("city_name_5")
                        .HasColumnType("text");

                    b.Property<string>("city_name_6")
                        .HasColumnType("text");

                    b.Property<string>("city_name_7")
                        .HasColumnType("text");

                    b.Property<string>("city_name_8")
                        .HasColumnType("text");

                    b.Property<string>("city_name_9")
                        .HasColumnType("text");

                    b.Property<string>("consumer_key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("consumer_key");

                    b.Property<DateTimeOffset?>("data_freshness_date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_freshness_date");

                    b.Property<string>("date_of_birth")
                        .HasColumnType("text");

                    b.Property<string>("deceased")
                        .HasColumnType("text");

                    b.Property<string>("delivery_point_code_1")
                        .HasColumnType("text");

                    b.Property<string>("delivery_point_code_10")
                        .HasColumnType("text");

                    b.Property<string>("delivery_point_code_2")
                        .HasColumnType("text");

                    b.Property<string>("delivery_point_code_3")
                        .HasColumnType("text");

                    b.Property<string>("delivery_point_code_4")
                        .HasColumnType("text");

                    b.Property<string>("delivery_point_code_5")
                        .HasColumnType("text");

                    b.Property<string>("delivery_point_code_6")
                        .HasColumnType("text");

                    b.Property<string>("delivery_point_code_7")
                        .HasColumnType("text");

                    b.Property<string>("delivery_point_code_8")
                        .HasColumnType("text");

                    b.Property<string>("delivery_point_code_9")
                        .HasColumnType("text");

                    b.Property<string>("delivery_point_validation_1")
                        .HasColumnType("text");

                    b.Property<string>("delivery_point_validation_10")
                        .HasColumnType("text");

                    b.Property<string>("delivery_point_validation_2")
                        .HasColumnType("text");

                    b.Property<string>("delivery_point_validation_3")
                        .HasColumnType("text");

                    b.Property<string>("delivery_point_validation_4")
                        .HasColumnType("text");

                    b.Property<string>("delivery_point_validation_5")
                        .HasColumnType("text");

                    b.Property<string>("delivery_point_validation_6")
                        .HasColumnType("text");

                    b.Property<string>("delivery_point_validation_7")
                        .HasColumnType("text");

                    b.Property<string>("delivery_point_validation_8")
                        .HasColumnType("text");

                    b.Property<string>("delivery_point_validation_9")
                        .HasColumnType("text");

                    b.Property<string>("economiccohortscode")
                        .HasColumnType("text");

                    b.Property<string>("email_1")
                        .HasColumnType("text");

                    b.Property<string>("email_10")
                        .HasColumnType("text");

                    b.Property<string>("email_11")
                        .HasColumnType("text");

                    b.Property<string>("email_12")
                        .HasColumnType("text");

                    b.Property<string>("email_13")
                        .HasColumnType("text");

                    b.Property<string>("email_14")
                        .HasColumnType("text");

                    b.Property<string>("email_15")
                        .HasColumnType("text");

                    b.Property<string>("email_2")
                        .HasColumnType("text");

                    b.Property<string>("email_3")
                        .HasColumnType("text");

                    b.Property<string>("email_4")
                        .HasColumnType("text");

                    b.Property<string>("email_5")
                        .HasColumnType("text");

                    b.Property<string>("email_6")
                        .HasColumnType("text");

                    b.Property<string>("email_7")
                        .HasColumnType("text");

                    b.Property<string>("email_8")
                        .HasColumnType("text");

                    b.Property<string>("email_9")
                        .HasColumnType("text");

                    b.Property<decimal?>("financialdurabilityindex")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("financialdurabilityscore")
                        .HasColumnType("numeric");

                    b.Property<string>("fips_code_1")
                        .HasColumnType("text");

                    b.Property<string>("fips_code_10")
                        .HasColumnType("text");

                    b.Property<string>("fips_code_2")
                        .HasColumnType("text");

                    b.Property<string>("fips_code_3")
                        .HasColumnType("text");

                    b.Property<string>("fips_code_4")
                        .HasColumnType("text");

                    b.Property<string>("fips_code_5")
                        .HasColumnType("text");

                    b.Property<string>("fips_code_6")
                        .HasColumnType("text");

                    b.Property<string>("fips_code_7")
                        .HasColumnType("text");

                    b.Property<string>("fips_code_8")
                        .HasColumnType("text");

                    b.Property<string>("fips_code_9")
                        .HasColumnType("text");

                    b.Property<string>("first_name")
                        .HasColumnType("text");

                    b.Property<string>("first_seen_date_primary_name")
                        .HasColumnType("text");

                    b.Property<string>("gender")
                        .HasColumnType("text");

                    b.Property<string>("house_number_1")
                        .HasColumnType("text");

                    b.Property<string>("house_number_10")
                        .HasColumnType("text");

                    b.Property<string>("house_number_2")
                        .HasColumnType("text");

                    b.Property<string>("house_number_3")
                        .HasColumnType("text");

                    b.Property<string>("house_number_4")
                        .HasColumnType("text");

                    b.Property<string>("house_number_5")
                        .HasColumnType("text");

                    b.Property<string>("house_number_6")
                        .HasColumnType("text");

                    b.Property<string>("house_number_7")
                        .HasColumnType("text");

                    b.Property<string>("house_number_8")
                        .HasColumnType("text");

                    b.Property<string>("house_number_9")
                        .HasColumnType("text");

                    b.Property<string>("idfa1")
                        .HasColumnType("text");

                    b.Property<string>("idfa2")
                        .HasColumnType("text");

                    b.Property<string>("idfa3")
                        .HasColumnType("text");

                    b.Property<string>("idfa4")
                        .HasColumnType("text");

                    b.Property<string>("idfa5")
                        .HasColumnType("text");

                    b.Property<decimal?>("income360_complete")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("income360_non_salary")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("income360_salary")
                        .HasColumnType("numeric");

                    b.Property<string>("ipaddress1")
                        .HasColumnType("text");

                    b.Property<string>("ipaddress2")
                        .HasColumnType("text");

                    b.Property<string>("last_name")
                        .HasColumnType("text");

                    b.Property<string>("last_seen_date_email_1")
                        .HasColumnType("text");

                    b.Property<string>("last_seen_date_email_10")
                        .HasColumnType("text");

                    b.Property<string>("last_seen_date_email_11")
                        .HasColumnType("text");

                    b.Property<string>("last_seen_date_email_12")
                        .HasColumnType("text");

                    b.Property<string>("last_seen_date_email_13")
                        .HasColumnType("text");

                    b.Property<string>("last_seen_date_email_14")
                        .HasColumnType("text");

                    b.Property<string>("last_seen_date_email_15")
                        .HasColumnType("text");

                    b.Property<string>("last_seen_date_email_2")
                        .HasColumnType("text");

                    b.Property<string>("last_seen_date_email_3")
                        .HasColumnType("text");

                    b.Property<string>("last_seen_date_email_4")
                        .HasColumnType("text");

                    b.Property<string>("last_seen_date_email_5")
                        .HasColumnType("text");

                    b.Property<string>("last_seen_date_email_6")
                        .HasColumnType("text");

                    b.Property<string>("last_seen_date_email_7")
                        .HasColumnType("text");

                    b.Property<string>("last_seen_date_email_8")
                        .HasColumnType("text");

                    b.Property<string>("last_seen_date_email_9")
                        .HasColumnType("text");

                    b.Property<string>("last_seen_date_phone_1")
                        .HasColumnType("text");

                    b.Property<string>("last_seen_date_phone_2")
                        .HasColumnType("text");

                    b.Property<string>("last_seen_date_phone_3")
                        .HasColumnType("text");

                    b.Property<string>("last_seen_date_phone_4")
                        .HasColumnType("text");

                    b.Property<string>("last_seen_date_phone_5")
                        .HasColumnType("text");

                    b.Property<string>("last_seen_date_primary_name")
                        .HasColumnType("text");

                    b.Property<string>("marketing_email_flag")
                        .HasColumnType("text");

                    b.Property<double>("match_confidence")
                        .HasPrecision(5, 4)
                        .HasColumnType("double precision")
                        .HasColumnName("match_confidence");

                    b.Property<string>("match_type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("match_type");

                    b.Property<string>("meta_revision")
                        .HasColumnType("text");

                    b.Property<string>("middle_name")
                        .HasColumnType("text");

                    b.Property<string>("mobile_phone_1")
                        .HasColumnType("text");

                    b.Property<string>("mobile_phone_2")
                        .HasColumnType("text");

                    b.Property<decimal?>("percent_balance_to_high_auto_finance_credit")
                        .HasColumnType("numeric");

                    b.Property<string>("phone_1")
                        .HasColumnType("text");

                    b.Property<string>("phone_2")
                        .HasColumnType("text");

                    b.Property<string>("phone_3")
                        .HasColumnType("text");

                    b.Property<string>("phone_4")
                        .HasColumnType("text");

                    b.Property<string>("phone_5")
                        .HasColumnType("text");

                    b.Property<string>("post_direction_1")
                        .HasColumnType("text");

                    b.Property<string>("post_direction_10")
                        .HasColumnType("text");

                    b.Property<string>("post_direction_2")
                        .HasColumnType("text");

                    b.Property<string>("post_direction_3")
                        .HasColumnType("text");

                    b.Property<string>("post_direction_4")
                        .HasColumnType("text");

                    b.Property<string>("post_direction_5")
                        .HasColumnType("text");

                    b.Property<string>("post_direction_6")
                        .HasColumnType("text");

                    b.Property<string>("post_direction_7")
                        .HasColumnType("text");

                    b.Property<string>("post_direction_8")
                        .HasColumnType("text");

                    b.Property<string>("post_direction_9")
                        .HasColumnType("text");

                    b.Property<string>("predirectional_1")
                        .HasColumnType("text");

                    b.Property<string>("predirectional_10")
                        .HasColumnType("text");

                    b.Property<string>("predirectional_2")
                        .HasColumnType("text");

                    b.Property<string>("predirectional_3")
                        .HasColumnType("text");

                    b.Property<string>("predirectional_4")
                        .HasColumnType("text");

                    b.Property<string>("predirectional_5")
                        .HasColumnType("text");

                    b.Property<string>("predirectional_6")
                        .HasColumnType("text");

                    b.Property<string>("predirectional_7")
                        .HasColumnType("text");

                    b.Property<string>("predirectional_8")
                        .HasColumnType("text");

                    b.Property<string>("predirectional_9")
                        .HasColumnType("text");

                    b.Property<string>("prefix")
                        .HasColumnType("text");

                    b.Property<decimal?>("spending_power")
                        .HasColumnType("numeric");

                    b.Property<string>("state_abbreviation_1")
                        .HasColumnType("text");

                    b.Property<string>("state_abbreviation_10")
                        .HasColumnType("text");

                    b.Property<string>("state_abbreviation_2")
                        .HasColumnType("text");

                    b.Property<string>("state_abbreviation_3")
                        .HasColumnType("text");

                    b.Property<string>("state_abbreviation_4")
                        .HasColumnType("text");

                    b.Property<string>("state_abbreviation_5")
                        .HasColumnType("text");

                    b.Property<string>("state_abbreviation_6")
                        .HasColumnType("text");

                    b.Property<string>("state_abbreviation_7")
                        .HasColumnType("text");

                    b.Property<string>("state_abbreviation_8")
                        .HasColumnType("text");

                    b.Property<string>("state_abbreviation_9")
                        .HasColumnType("text");

                    b.Property<string>("street_name_1")
                        .HasColumnType("text");

                    b.Property<string>("street_name_10")
                        .HasColumnType("text");

                    b.Property<string>("street_name_2")
                        .HasColumnType("text");

                    b.Property<string>("street_name_3")
                        .HasColumnType("text");

                    b.Property<string>("street_name_4")
                        .HasColumnType("text");

                    b.Property<string>("street_name_5")
                        .HasColumnType("text");

                    b.Property<string>("street_name_6")
                        .HasColumnType("text");

                    b.Property<string>("street_name_7")
                        .HasColumnType("text");

                    b.Property<string>("street_name_8")
                        .HasColumnType("text");

                    b.Property<string>("street_name_9")
                        .HasColumnType("text");

                    b.Property<string>("street_suffix_1")
                        .HasColumnType("text");

                    b.Property<string>("street_suffix_10")
                        .HasColumnType("text");

                    b.Property<string>("street_suffix_2")
                        .HasColumnType("text");

                    b.Property<string>("street_suffix_3")
                        .HasColumnType("text");

                    b.Property<string>("street_suffix_4")
                        .HasColumnType("text");

                    b.Property<string>("street_suffix_5")
                        .HasColumnType("text");

                    b.Property<string>("street_suffix_6")
                        .HasColumnType("text");

                    b.Property<string>("street_suffix_7")
                        .HasColumnType("text");

                    b.Property<string>("street_suffix_8")
                        .HasColumnType("text");

                    b.Property<string>("street_suffix_9")
                        .HasColumnType("text");

                    b.Property<string>("suffix")
                        .HasColumnType("text");

                    b.Property<string>("transaction_date_1")
                        .HasColumnType("text");

                    b.Property<string>("transaction_date_10")
                        .HasColumnType("text");

                    b.Property<string>("transaction_date_2")
                        .HasColumnType("text");

                    b.Property<string>("transaction_date_3")
                        .HasColumnType("text");

                    b.Property<string>("transaction_date_4")
                        .HasColumnType("text");

                    b.Property<string>("transaction_date_5")
                        .HasColumnType("text");

                    b.Property<string>("transaction_date_6")
                        .HasColumnType("text");

                    b.Property<string>("transaction_date_7")
                        .HasColumnType("text");

                    b.Property<string>("transaction_date_8")
                        .HasColumnType("text");

                    b.Property<string>("transaction_date_9")
                        .HasColumnType("text");

                    b.Property<string>("unit_number_1")
                        .HasColumnType("text");

                    b.Property<string>("unit_number_10")
                        .HasColumnType("text");

                    b.Property<string>("unit_number_2")
                        .HasColumnType("text");

                    b.Property<string>("unit_number_3")
                        .HasColumnType("text");

                    b.Property<string>("unit_number_4")
                        .HasColumnType("text");

                    b.Property<string>("unit_number_5")
                        .HasColumnType("text");

                    b.Property<string>("unit_number_6")
                        .HasColumnType("text");

                    b.Property<string>("unit_number_7")
                        .HasColumnType("text");

                    b.Property<string>("unit_number_8")
                        .HasColumnType("text");

                    b.Property<string>("unit_number_9")
                        .HasColumnType("text");

                    b.Property<string>("unit_type_1")
                        .HasColumnType("text");

                    b.Property<string>("unit_type_10")
                        .HasColumnType("text");

                    b.Property<string>("unit_type_2")
                        .HasColumnType("text");

                    b.Property<string>("unit_type_3")
                        .HasColumnType("text");

                    b.Property<string>("unit_type_4")
                        .HasColumnType("text");

                    b.Property<string>("unit_type_5")
                        .HasColumnType("text");

                    b.Property<string>("unit_type_6")
                        .HasColumnType("text");

                    b.Property<string>("unit_type_7")
                        .HasColumnType("text");

                    b.Property<string>("unit_type_8")
                        .HasColumnType("text");

                    b.Property<string>("unit_type_9")
                        .HasColumnType("text");

                    b.Property<string>("uuid")
                        .HasColumnType("text");

                    b.Property<decimal?>("vaa")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("vac")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("vad")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("vae")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("vaf")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("vag")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("vah")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("vai")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("vaj")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("vak")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("val")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("vam")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("van")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("vantage_score_neighborhood_risk_score")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("vao")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("vap")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("vaq")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("vas")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("vat")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("vau")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("vav")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("vaw")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("vax")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("vay")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("vaz")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("vba")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("vbb")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("vbc")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("vbd")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("vbe")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("vbf")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("vbg")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("vbh")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("vbi")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("vbj")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("vbk")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("vbl")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("vbm")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("vbn")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("vbo")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("vbp")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("vbq")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("vbr")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("vbs")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("vbt")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("vbu")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("vbv")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("vbw")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("vbx")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("vby")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("vbz")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("vc")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("vca")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("vcb")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("vcc")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("vcd")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("vce")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("vcf")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("vcg")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("vch")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("vci")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("vcj")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("vck")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("vcl")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("vcm")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("vcn")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("vco")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("vcp")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("vcq")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("vcr")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("vcs")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("vct")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("vcu")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("vcv")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("vcw")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("vcx")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("vcy")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("vcz")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("vda")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("vdb")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("vdc")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("vdd")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("vde")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("vdf")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("vdg")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("vdh")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("vdi")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("vdj")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("vdk")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("vdl")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("vdm")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("vdn")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("vdo")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("vdp")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("vdq")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("vdr")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("vds")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("vf")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("vg")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("vh")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("vj")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("vk")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("vl")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("vm")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("vn")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("vo")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("vp")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("vq")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("vr")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("vs")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("vt")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("vy")
                        .HasColumnType("numeric");

                    b.Property<string>("z4_1")
                        .HasColumnType("text");

                    b.Property<string>("z4_10")
                        .HasColumnType("text");

                    b.Property<string>("z4_2")
                        .HasColumnType("text");

                    b.Property<string>("z4_3")
                        .HasColumnType("text");

                    b.Property<string>("z4_4")
                        .HasColumnType("text");

                    b.Property<string>("z4_5")
                        .HasColumnType("text");

                    b.Property<string>("z4_6")
                        .HasColumnType("text");

                    b.Property<string>("z4_7")
                        .HasColumnType("text");

                    b.Property<string>("z4_8")
                        .HasColumnType("text");

                    b.Property<string>("z4_9")
                        .HasColumnType("text");

                    b.Property<string>("z4_type_1")
                        .HasColumnType("text");

                    b.Property<string>("z4_type_10")
                        .HasColumnType("text");

                    b.Property<string>("z4_type_2")
                        .HasColumnType("text");

                    b.Property<string>("z4_type_3")
                        .HasColumnType("text");

                    b.Property<string>("z4_type_4")
                        .HasColumnType("text");

                    b.Property<string>("z4_type_5")
                        .HasColumnType("text");

                    b.Property<string>("z4_type_6")
                        .HasColumnType("text");

                    b.Property<string>("z4_type_7")
                        .HasColumnType("text");

                    b.Property<string>("z4_type_8")
                        .HasColumnType("text");

                    b.Property<string>("z4_type_9")
                        .HasColumnType("text");

                    b.Property<string>("zip_1")
                        .HasColumnType("text");

                    b.Property<string>("zip_10")
                        .HasColumnType("text");

                    b.Property<string>("zip_2")
                        .HasColumnType("text");

                    b.Property<string>("zip_3")
                        .HasColumnType("text");

                    b.Property<string>("zip_4")
                        .HasColumnType("text");

                    b.Property<string>("zip_5")
                        .HasColumnType("text");

                    b.Property<string>("zip_6")
                        .HasColumnType("text");

                    b.Property<string>("zip_7")
                        .HasColumnType("text");

                    b.Property<string>("zip_8")
                        .HasColumnType("text");

                    b.Property<string>("zip_9")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_consumer_enrichments_created_at");

                    b.HasIndex("consumer_key")
                        .HasDatabaseName("ix_consumer_enrichments_consumer_key");

                    b.HasIndex("mobile_phone_1")
                        .HasDatabaseName("ix_consumer_enrichments_mobile_phone_1");

                    b.HasIndex("phone_1")
                        .HasDatabaseName("ix_consumer_enrichments_phone_1");

                    b.ToTable("consumer_enrichments", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
