// <auto-generated />
using System;
using EquifaxEnrichmentAPI.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EquifaxEnrichmentAPI.Infrastructure.Migrations
{
    [DbContext(typeof(EnrichmentDbContext))]
    partial class EnrichmentDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EquifaxEnrichmentAPI.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("BuyerId")
                        .HasColumnType("uuid")
                        .HasColumnName("buyer_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip_address");

                    b.Property<string>("PermissiblePurpose")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("permissible_purpose");

                    b.Property<string>("PhoneHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("phone_hash");

                    b.Property<string>("Response")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("response");

                    b.Property<int>("StatusCode")
                        .HasColumnType("integer")
                        .HasColumnName("status_code");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("timestamp")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp")
                        .IsDescending()
                        .HasDatabaseName("ix_audit_logs_timestamp");

                    b.HasIndex("BuyerId", "Timestamp")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_audit_logs_buyer_id_timestamp");

                    b.HasIndex("PhoneHash", "Timestamp")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_audit_logs_phone_hash_timestamp");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("EquifaxEnrichmentAPI.Domain.Entities.Buyer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ApiKeyHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("api_key_hash");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ApiKeyHash")
                        .IsUnique()
                        .HasDatabaseName("ix_buyers_api_key_hash_unique");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_buyers_created_at");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_buyers_is_active");

                    b.ToTable("buyers", (string)null);
                });

            modelBuilder.Entity("EquifaxEnrichmentAPI.Domain.Entities.ConsumerEnrichment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AddressesJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("addresses_json");

                    b.Property<string>("ConsumerKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("consumer_key");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("DataFreshnessDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_freshness_date");

                    b.Property<string>("FinancialJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("financial_json");

                    b.Property<double>("MatchConfidence")
                        .HasPrecision(5, 4)
                        .HasColumnType("double precision")
                        .HasColumnName("match_confidence");

                    b.Property<string>("MatchType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("match_type");

                    b.Property<string>("NormalizedPhone")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("normalized_phone");

                    b.Property<string>("PersonalInfoJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("personal_info_json");

                    b.Property<string>("Phone1")
                        .HasColumnType("text");

                    b.Property<string>("Phone10")
                        .HasColumnType("text");

                    b.Property<string>("Phone2")
                        .HasColumnType("text");

                    b.Property<string>("Phone3")
                        .HasColumnType("text");

                    b.Property<string>("Phone4")
                        .HasColumnType("text");

                    b.Property<string>("Phone5")
                        .HasColumnType("text");

                    b.Property<string>("Phone6")
                        .HasColumnType("text");

                    b.Property<string>("Phone7")
                        .HasColumnType("text");

                    b.Property<string>("Phone8")
                        .HasColumnType("text");

                    b.Property<string>("Phone9")
                        .HasColumnType("text");

                    b.Property<string>("PhonesJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phones_json");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ConsumerKey")
                        .HasDatabaseName("ix_consumer_enrichments_consumer_key");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_consumer_enrichments_created_at");

                    b.HasIndex("NormalizedPhone")
                        .IsUnique()
                        .HasDatabaseName("ix_consumer_enrichments_normalized_phone_unique");

                    b.ToTable("consumer_enrichments", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
